### ISSUE TITLE
Fail gracefully if versionbot is true but not present

### ISSUE THREAD

**Issue by klutchell** [balena-io/deploy-to-balena-action#159]
If versionbot is enabled but no checks are found we don't provide a useful message.
```
git version 2.34.2
Initializing SDK for [https://api.balena-cloud.com)](https://api.balena-cloud.com%29/)
Error: API rate limit exceeded for installation ID 10067874.
Error: Failed to fetch check runs for: balena-io-playground/bCat:ff8c4136c0[55](https://github.com/balena-io-playground/bCat/runs/6291917758?check_suite_focus=true#step:6:55)99775a801f87cc216c79bbeb1968
```
It might be nice to provide an earlier check to see if versionbot is detected, or maybe even automatically enable/disable the flag.

**Comment by hslatman** [comment]
Encountered this issue too. 

Some notes here: https://github.com/hslatman/tailscale-balena-block/pull/2. My debugging progress here: https://github.com/hslatman/tailscale-balena-block/pull/3.

**Comment by klutchell** [comment]
To clarify the issue:

If `versionbot: true` is set in the action config, then the [VersionBot3](https://github.com/apps/versionbot3) GH app must also be enabled on the repo or the action will fail without a helpful message.

The workaround is to set `versionbot: false` in the action config or enable VersionBot3 GH app on the repo.

**Comment by klutchell** [comment]
VersionBot is being deprecated so closing this feature request.
