### ISSUE TITLE
Update block|fleet|app release notes from git log or CHANGELOG.md or release-notes, etc.

### ISSUE THREAD

**Issue by ab77** [balena-io/deploy-to-balena-action#194]
(e.g.)

          curl --retry 3 --fail \
            -X PATCH "https://api.balena-cloud.com/v6/release?\$filter=belongs_to__application%20eq%20${fleet_id}%20and%20id%20eq%20${{ needs.publish.outputs.release_id }}" \
            -H 'Content-Type: application/json' \
            -H 'Authorization: Bearer ${{ secrets.BALENA_API_KEY }}' \
            -d '{"note":"${{ env.RELEASE_NOTES }}"}'

**Comment by klutchell** [comment]
It seems like this is partially resolved by https://github.com/balena-io/deploy-to-balena-action/pull/274?

**Comment by klutchell** [comment]
@ab77 ?

**Comment by ab77** [comment]
> @ab77 ?

I'll have to find and update y personal project where I originally hacked around this. We may also be the old manual approach somewhere internally. Need to find and replace also.
