### ISSUE TITLE
Warning: The `set-output` command is deprecated and will be disabled soon.

### ISSUE THREAD

**Issue by maggie0002** [balena-io/deploy-to-balena-action#233]
There are two warnings in the logs of builds like the below when using the action. 

```
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

Here is the GitHub notification on it: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

I can't see any instances of `set-output` in the code, so it is probably just a matter of bumping a few packages up to start using the versions that have updated this. 

Here is an example for `@actions/core`: https://github.com/actions/toolkit/issues/1218#issuecomment-1292412551

**Comment by klutchell** [comment]
We are calling the `setOutput` function from the `@actions/core` library, so we either need to bump it as you said, or maybe there is a new function call we should be using.
https://github.com/balena-io/deploy-to-balena-action/blob/c9d7b49b03ee6d083c6298d48e79cf93a7678914/src/action.ts#L143-L144

**Comment by klutchell** [comment]
This Renovate PR should have fixed it, but we closed it.
https://github.com/balena-io/deploy-to-balena-action/pull/221
