### ISSUE TITLE
v0.24.0 broke push

### ISSUE THREAD

**Issue by juliankock** [balena-io/deploy-to-balena-action#240]
Hey Balena.

We experience that v0.24.0 broke our deploy.

Here is the output:
Error: request to [https://api.balena-cloud.com)/ 
reason: getaddrinfo ENOTFOUND api.balena-cloud.com)

It looks like an ending parenthesis is added.

**Comment by klutchell** [comment]
@juliankock is this still an issue for you in v0.26.0?

Are you setting the `environment` input in your workflow or just using the defaults?

**Comment by juliankock** [comment]
Works now
