### ISSUE TITLE
allow specifying which branch action can finalize on

### ISSUE THREAD

**Issue by 20k-ultra** [balena-io/deploy-to-balena-action#4]
The action uses the [default_branch](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-branches#about-the-default-branch) to know when the code has reach its final destination and makes a release final. 

However, if the branch we want to finalize releases on isn't the default_branch which each repository have then we should allow providing the default_branch as an input.

**Comment by lordspite** [comment]
Can I get a review on pr?
